### ISSUE TITLE
Unable to run the example for some reason

### ISSUE THREAD

**Issue by robodreamer** [PerlinWarp/MatplotLeap#5]
Hi, I was able to install the driver for leapmotion but when I run your plot_hand.py example, I get this error. Any clues?

```
$~/Projects/repos/MatplotLeap$ python3 plot_hand.py 
Traceback (most recent call last):
  File "plot_hand.py", line 3, in <module>
    import Leap
  File "/home/apark/Projects/repos/MatplotLeap/Leap.py", line 28, in <module>
    LeapPython = swig_import_helper()
  File "/home/apark/Projects/repos/MatplotLeap/Leap.py", line 24, in swig_import_helper
    _mod = imp.load_module('LeapPython', fp, pathname, description)
  File "/usr/lib/python3.8/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libLeap.so: cannot open shared object file: No such file or directory
```

**Comment by robodreamer** [comment]
No worries. It was due to not adding the `LD_LIBRARY_PATH` corretly. This line below solved it!

`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`
